package com.mybatis.dao;

import com.mybatis.model.MarketIndexHistory;
import com.mybatis.model.MarketIndexHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketIndexHistoryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index_history
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int countByExample(MarketIndexHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index_history
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int deleteByExample(MarketIndexHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index_history
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index_history
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int insert(MarketIndexHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index_history
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int insertSelective(MarketIndexHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index_history
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    List<MarketIndexHistory> selectByExample(MarketIndexHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index_history
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    MarketIndexHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index_history
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") MarketIndexHistory record, @Param("example") MarketIndexHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index_history
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByExample(@Param("record") MarketIndexHistory record, @Param("example") MarketIndexHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index_history
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByPrimaryKeySelective(MarketIndexHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index_history
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByPrimaryKey(MarketIndexHistory record);
}