package com.mybatis.dao;

import com.mybatis.model.MarketIndex;
import com.mybatis.model.MarketIndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketIndexDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int countByExample(MarketIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int deleteByExample(MarketIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int insert(MarketIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int insertSelective(MarketIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    List<MarketIndex> selectByExample(MarketIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    MarketIndex selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") MarketIndex record, @Param("example") MarketIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByExample(@Param("record") MarketIndex record, @Param("example") MarketIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByPrimaryKeySelective(MarketIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByPrimaryKey(MarketIndex record);
}