package com.mybatis.dao;

import com.mybatis.model.StockExtendInfo;
import com.mybatis.model.StockExtendInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockExtendInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int countByExample(StockExtendInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int deleteByExample(StockExtendInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int insert(StockExtendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int insertSelective(StockExtendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    List<StockExtendInfo> selectByExample(StockExtendInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    StockExtendInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") StockExtendInfo record, @Param("example") StockExtendInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByExample(@Param("record") StockExtendInfo record, @Param("example") StockExtendInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByPrimaryKeySelective(StockExtendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByPrimaryKey(StockExtendInfo record);
}