package com.mybatis.dao;

import com.mybatis.model.StockHistory;
import com.mybatis.model.StockHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface StockHistoryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    int countByExample(StockHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    int deleteByExample(StockHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    int insert(StockHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    int insertSelective(StockHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    List<StockHistory> selectByExampleWithRowbounds(StockHistoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    List<StockHistory> selectByExample(StockHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    StockHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") StockHistory record, @Param("example") StockHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    int updateByExample(@Param("record") StockHistory record, @Param("example") StockHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    int updateByPrimaryKeySelective(StockHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    int updateByPrimaryKey(StockHistory record);
}