package com.mybatis.dao;

import com.mybatis.model.StockMa;
import com.mybatis.model.StockMaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockMaDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int countByExample(StockMaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int deleteByExample(StockMaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int insert(StockMa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int insertSelective(StockMa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    List<StockMa> selectByExample(StockMaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    StockMa selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") StockMa record, @Param("example") StockMaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int updateByExample(@Param("record") StockMa record, @Param("example") StockMaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int updateByPrimaryKeySelective(StockMa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int updateByPrimaryKey(StockMa record);
}