package com.mybatis.dao;

import com.mybatis.model.StockCategory;
import com.mybatis.model.StockCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockCategoryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int countByExample(StockCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int deleteByExample(StockCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int insert(StockCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int insertSelective(StockCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    List<StockCategory> selectByExample(StockCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    StockCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") StockCategory record, @Param("example") StockCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByExample(@Param("record") StockCategory record, @Param("example") StockCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByPrimaryKeySelective(StockCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByPrimaryKey(StockCategory record);
}