package com.mybatis.dao;

import com.mybatis.model.StockTradingDate;
import com.mybatis.model.StockTradingDateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockTradingDateDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int countByExample(StockTradingDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int deleteByExample(StockTradingDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int insert(StockTradingDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int insertSelective(StockTradingDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    List<StockTradingDate> selectByExample(StockTradingDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    StockTradingDate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") StockTradingDate record, @Param("example") StockTradingDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int updateByExample(@Param("record") StockTradingDate record, @Param("example") StockTradingDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int updateByPrimaryKeySelective(StockTradingDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int updateByPrimaryKey(StockTradingDate record);
}