package com.mybatis.dao;

import com.mybatis.model.StockKdj;
import com.mybatis.model.StockKdjExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockKdjDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockkdj
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int countByExample(StockKdjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockkdj
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int deleteByExample(StockKdjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockkdj
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockkdj
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int insert(StockKdj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockkdj
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int insertSelective(StockKdj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockkdj
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    List<StockKdj> selectByExample(StockKdjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockkdj
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    StockKdj selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockkdj
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") StockKdj record, @Param("example") StockKdjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockkdj
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByExample(@Param("record") StockKdj record, @Param("example") StockKdjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockkdj
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByPrimaryKeySelective(StockKdj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockkdj
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByPrimaryKey(StockKdj record);
}