package com.mybatis.dao;

import com.mybatis.model.StockBuysellPoint;
import com.mybatis.model.StockBuysellPointExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockBuysellPointDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_buysell_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int countByExample(StockBuysellPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_buysell_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int deleteByExample(StockBuysellPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_buysell_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_buysell_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int insert(StockBuysellPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_buysell_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int insertSelective(StockBuysellPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_buysell_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    List<StockBuysellPoint> selectByExample(StockBuysellPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_buysell_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    StockBuysellPoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_buysell_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") StockBuysellPoint record, @Param("example") StockBuysellPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_buysell_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByExample(@Param("record") StockBuysellPoint record, @Param("example") StockBuysellPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_buysell_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByPrimaryKeySelective(StockBuysellPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_buysell_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByPrimaryKey(StockBuysellPoint record);
}