package com.mybatis.dao;

import com.mybatis.model.StockCategoryRef;
import com.mybatis.model.StockCategoryRefExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockCategoryRefDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category_ref
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int countByExample(StockCategoryRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category_ref
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int deleteByExample(StockCategoryRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category_ref
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category_ref
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int insert(StockCategoryRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category_ref
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int insertSelective(StockCategoryRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category_ref
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    List<StockCategoryRef> selectByExample(StockCategoryRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category_ref
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    StockCategoryRef selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category_ref
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") StockCategoryRef record, @Param("example") StockCategoryRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category_ref
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByExample(@Param("record") StockCategoryRef record, @Param("example") StockCategoryRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category_ref
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByPrimaryKeySelective(StockCategoryRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category_ref
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    int updateByPrimaryKey(StockCategoryRef record);
}