package com.mybatis.dao;

import com.mybatis.model.StockMacd;
import com.mybatis.model.StockMacdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockMacdDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockmacd
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int countByExample(StockMacdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockmacd
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int deleteByExample(StockMacdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockmacd
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockmacd
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int insert(StockMacd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockmacd
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int insertSelective(StockMacd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockmacd
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    List<StockMacd> selectByExample(StockMacdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockmacd
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    StockMacd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockmacd
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") StockMacd record, @Param("example") StockMacdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockmacd
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int updateByExample(@Param("record") StockMacd record, @Param("example") StockMacdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockmacd
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int updateByPrimaryKeySelective(StockMacd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockmacd
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    int updateByPrimaryKey(StockMacd record);
}