package com.mybatis.model;

public class HypothesisResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hypothesis_result.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hypothesis_result.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hypothesis_result.hypo
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private String hypo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hypothesis_result.success
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer success;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hypothesis_result.fail
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer fail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hypothesis_result.percentage
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Float percentage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hypothesis_result.comment
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hypothesis_result
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public HypothesisResult(Integer id, Integer stockId, String hypo, Integer success, Integer fail, Float percentage, String comment) {
        this.id = id;
        this.stockId = stockId;
        this.hypo = hypo;
        this.success = success;
        this.fail = fail;
        this.percentage = percentage;
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hypothesis_result
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public HypothesisResult() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hypothesis_result.id
     *
     * @return the value of hypothesis_result.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hypothesis_result.id
     *
     * @param id the value for hypothesis_result.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hypothesis_result.stock_id
     *
     * @return the value of hypothesis_result.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hypothesis_result.stock_id
     *
     * @param stockId the value for hypothesis_result.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hypothesis_result.hypo
     *
     * @return the value of hypothesis_result.hypo
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getHypo() {
        return hypo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hypothesis_result.hypo
     *
     * @param hypo the value for hypothesis_result.hypo
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setHypo(String hypo) {
        this.hypo = hypo == null ? null : hypo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hypothesis_result.success
     *
     * @return the value of hypothesis_result.success
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hypothesis_result.success
     *
     * @param success the value for hypothesis_result.success
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setSuccess(Integer success) {
        this.success = success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hypothesis_result.fail
     *
     * @return the value of hypothesis_result.fail
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getFail() {
        return fail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hypothesis_result.fail
     *
     * @param fail the value for hypothesis_result.fail
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setFail(Integer fail) {
        this.fail = fail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hypothesis_result.percentage
     *
     * @return the value of hypothesis_result.percentage
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Float getPercentage() {
        return percentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hypothesis_result.percentage
     *
     * @param percentage the value for hypothesis_result.percentage
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setPercentage(Float percentage) {
        this.percentage = percentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hypothesis_result.comment
     *
     * @return the value of hypothesis_result.comment
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hypothesis_result.comment
     *
     * @param comment the value for hypothesis_result.comment
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}