package com.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class MarketIndexHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_index_history.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_index_history.market_index_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer marketIndexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_index_history.trading_date_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer tradingDateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_index_history.min_price
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private BigDecimal minPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_index_history.trade_num
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Long tradeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_index_history.trade_money
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Long tradeMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_index_history.diff_money
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private BigDecimal diffMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_index_history.close_price
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private BigDecimal closePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_index_history.open_price
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private BigDecimal openPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_index_history.max_price
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private BigDecimal maxPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_index_history.diff_rate
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private BigDecimal diffRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_index_history.date
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index_history
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public MarketIndexHistory(Integer id, Integer marketIndexId, Integer tradingDateId, BigDecimal minPrice, Long tradeNum, Long tradeMoney, BigDecimal diffMoney, BigDecimal closePrice, BigDecimal openPrice, BigDecimal maxPrice, BigDecimal diffRate, Date date) {
        this.id = id;
        this.marketIndexId = marketIndexId;
        this.tradingDateId = tradingDateId;
        this.minPrice = minPrice;
        this.tradeNum = tradeNum;
        this.tradeMoney = tradeMoney;
        this.diffMoney = diffMoney;
        this.closePrice = closePrice;
        this.openPrice = openPrice;
        this.maxPrice = maxPrice;
        this.diffRate = diffRate;
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index_history
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public MarketIndexHistory() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_index_history.id
     *
     * @return the value of market_index_history.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_index_history.id
     *
     * @param id the value for market_index_history.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_index_history.market_index_id
     *
     * @return the value of market_index_history.market_index_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getMarketIndexId() {
        return marketIndexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_index_history.market_index_id
     *
     * @param marketIndexId the value for market_index_history.market_index_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setMarketIndexId(Integer marketIndexId) {
        this.marketIndexId = marketIndexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_index_history.trading_date_id
     *
     * @return the value of market_index_history.trading_date_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getTradingDateId() {
        return tradingDateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_index_history.trading_date_id
     *
     * @param tradingDateId the value for market_index_history.trading_date_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setTradingDateId(Integer tradingDateId) {
        this.tradingDateId = tradingDateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_index_history.min_price
     *
     * @return the value of market_index_history.min_price
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public BigDecimal getMinPrice() {
        return minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_index_history.min_price
     *
     * @param minPrice the value for market_index_history.min_price
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setMinPrice(BigDecimal minPrice) {
        this.minPrice = minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_index_history.trade_num
     *
     * @return the value of market_index_history.trade_num
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Long getTradeNum() {
        return tradeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_index_history.trade_num
     *
     * @param tradeNum the value for market_index_history.trade_num
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setTradeNum(Long tradeNum) {
        this.tradeNum = tradeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_index_history.trade_money
     *
     * @return the value of market_index_history.trade_money
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Long getTradeMoney() {
        return tradeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_index_history.trade_money
     *
     * @param tradeMoney the value for market_index_history.trade_money
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setTradeMoney(Long tradeMoney) {
        this.tradeMoney = tradeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_index_history.diff_money
     *
     * @return the value of market_index_history.diff_money
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public BigDecimal getDiffMoney() {
        return diffMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_index_history.diff_money
     *
     * @param diffMoney the value for market_index_history.diff_money
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setDiffMoney(BigDecimal diffMoney) {
        this.diffMoney = diffMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_index_history.close_price
     *
     * @return the value of market_index_history.close_price
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public BigDecimal getClosePrice() {
        return closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_index_history.close_price
     *
     * @param closePrice the value for market_index_history.close_price
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setClosePrice(BigDecimal closePrice) {
        this.closePrice = closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_index_history.open_price
     *
     * @return the value of market_index_history.open_price
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public BigDecimal getOpenPrice() {
        return openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_index_history.open_price
     *
     * @param openPrice the value for market_index_history.open_price
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setOpenPrice(BigDecimal openPrice) {
        this.openPrice = openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_index_history.max_price
     *
     * @return the value of market_index_history.max_price
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public BigDecimal getMaxPrice() {
        return maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_index_history.max_price
     *
     * @param maxPrice the value for market_index_history.max_price
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setMaxPrice(BigDecimal maxPrice) {
        this.maxPrice = maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_index_history.diff_rate
     *
     * @return the value of market_index_history.diff_rate
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public BigDecimal getDiffRate() {
        return diffRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_index_history.diff_rate
     *
     * @param diffRate the value for market_index_history.diff_rate
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setDiffRate(BigDecimal diffRate) {
        this.diffRate = diffRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_index_history.date
     *
     * @return the value of market_index_history.date
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_index_history.date
     *
     * @param date the value for market_index_history.date
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }
}