package com.mybatis.model;

public class MarketIndex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_index.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_index.index_name
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private String indexName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public MarketIndex(Integer id, String indexName) {
        this.id = id;
        this.indexName = indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_index
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public MarketIndex() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_index.id
     *
     * @return the value of market_index.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_index.id
     *
     * @param id the value for market_index.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_index.index_name
     *
     * @return the value of market_index.index_name
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_index.index_name
     *
     * @param indexName the value for market_index.index_name
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName == null ? null : indexName.trim();
    }
}