package com.mybatis.model;

public class StockBuysellPoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_buysell_point.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_buysell_point.buy_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer buyPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_buysell_point.sell_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer sellPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_buysell_point.stock_history_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer stockHistoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_buysell_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public StockBuysellPoint(Integer id, Integer buyPoint, Integer sellPoint, Integer stockHistoryId) {
        this.id = id;
        this.buyPoint = buyPoint;
        this.sellPoint = sellPoint;
        this.stockHistoryId = stockHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_buysell_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public StockBuysellPoint() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_buysell_point.id
     *
     * @return the value of stock_buysell_point.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_buysell_point.id
     *
     * @param id the value for stock_buysell_point.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_buysell_point.buy_point
     *
     * @return the value of stock_buysell_point.buy_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getBuyPoint() {
        return buyPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_buysell_point.buy_point
     *
     * @param buyPoint the value for stock_buysell_point.buy_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setBuyPoint(Integer buyPoint) {
        this.buyPoint = buyPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_buysell_point.sell_point
     *
     * @return the value of stock_buysell_point.sell_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getSellPoint() {
        return sellPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_buysell_point.sell_point
     *
     * @param sellPoint the value for stock_buysell_point.sell_point
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setSellPoint(Integer sellPoint) {
        this.sellPoint = sellPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_buysell_point.stock_history_id
     *
     * @return the value of stock_buysell_point.stock_history_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getStockHistoryId() {
        return stockHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_buysell_point.stock_history_id
     *
     * @param stockHistoryId the value for stock_buysell_point.stock_history_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setStockHistoryId(Integer stockHistoryId) {
        this.stockHistoryId = stockHistoryId;
    }
}