package com.mybatis.model;

import java.math.BigDecimal;

public class StockIncomeStatementHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_income_statement_history.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_income_statement_history.year
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_income_statement_history.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_income_statement_history.revenue
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private BigDecimal revenue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_income_statement_history.net_profit
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private BigDecimal netProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_income_statement_history.earnings_per_share
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private BigDecimal earningsPerShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_income_statement_history.total_assets
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private BigDecimal totalAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_income_statement_history.shareholder_amount
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer shareholderAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_income_statement_history
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public StockIncomeStatementHistory(Integer id, Integer year, Integer stockId, BigDecimal revenue, BigDecimal netProfit, BigDecimal earningsPerShare, BigDecimal totalAssets, Integer shareholderAmount) {
        this.id = id;
        this.year = year;
        this.stockId = stockId;
        this.revenue = revenue;
        this.netProfit = netProfit;
        this.earningsPerShare = earningsPerShare;
        this.totalAssets = totalAssets;
        this.shareholderAmount = shareholderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_income_statement_history
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public StockIncomeStatementHistory() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_income_statement_history.id
     *
     * @return the value of stock_income_statement_history.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_income_statement_history.id
     *
     * @param id the value for stock_income_statement_history.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_income_statement_history.year
     *
     * @return the value of stock_income_statement_history.year
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_income_statement_history.year
     *
     * @param year the value for stock_income_statement_history.year
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_income_statement_history.stock_id
     *
     * @return the value of stock_income_statement_history.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_income_statement_history.stock_id
     *
     * @param stockId the value for stock_income_statement_history.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_income_statement_history.revenue
     *
     * @return the value of stock_income_statement_history.revenue
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public BigDecimal getRevenue() {
        return revenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_income_statement_history.revenue
     *
     * @param revenue the value for stock_income_statement_history.revenue
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setRevenue(BigDecimal revenue) {
        this.revenue = revenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_income_statement_history.net_profit
     *
     * @return the value of stock_income_statement_history.net_profit
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public BigDecimal getNetProfit() {
        return netProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_income_statement_history.net_profit
     *
     * @param netProfit the value for stock_income_statement_history.net_profit
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setNetProfit(BigDecimal netProfit) {
        this.netProfit = netProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_income_statement_history.earnings_per_share
     *
     * @return the value of stock_income_statement_history.earnings_per_share
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public BigDecimal getEarningsPerShare() {
        return earningsPerShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_income_statement_history.earnings_per_share
     *
     * @param earningsPerShare the value for stock_income_statement_history.earnings_per_share
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setEarningsPerShare(BigDecimal earningsPerShare) {
        this.earningsPerShare = earningsPerShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_income_statement_history.total_assets
     *
     * @return the value of stock_income_statement_history.total_assets
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public BigDecimal getTotalAssets() {
        return totalAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_income_statement_history.total_assets
     *
     * @param totalAssets the value for stock_income_statement_history.total_assets
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setTotalAssets(BigDecimal totalAssets) {
        this.totalAssets = totalAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_income_statement_history.shareholder_amount
     *
     * @return the value of stock_income_statement_history.shareholder_amount
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getShareholderAmount() {
        return shareholderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_income_statement_history.shareholder_amount
     *
     * @param shareholderAmount the value for stock_income_statement_history.shareholder_amount
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setShareholderAmount(Integer shareholderAmount) {
        this.shareholderAmount = shareholderAmount;
    }
}