package com.mybatis.model;

public class StockCategoryRef {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_category_ref.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_category_ref.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_category_ref.category_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category_ref
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public StockCategoryRef(Integer id, Integer stockId, Integer categoryId) {
        this.id = id;
        this.stockId = stockId;
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category_ref
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public StockCategoryRef() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_category_ref.id
     *
     * @return the value of stock_category_ref.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_category_ref.id
     *
     * @param id the value for stock_category_ref.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_category_ref.stock_id
     *
     * @return the value of stock_category_ref.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_category_ref.stock_id
     *
     * @param stockId the value for stock_category_ref.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_category_ref.category_id
     *
     * @return the value of stock_category_ref.category_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_category_ref.category_id
     *
     * @param categoryId the value for stock_category_ref.category_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
}