package com.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class StockExtendInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public StockExtendInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStockIdIsNull() {
            addCriterion("stock_id is null");
            return (Criteria) this;
        }

        public Criteria andStockIdIsNotNull() {
            addCriterion("stock_id is not null");
            return (Criteria) this;
        }

        public Criteria andStockIdEqualTo(Integer value) {
            addCriterion("stock_id =", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdNotEqualTo(Integer value) {
            addCriterion("stock_id <>", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdGreaterThan(Integer value) {
            addCriterion("stock_id >", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("stock_id >=", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdLessThan(Integer value) {
            addCriterion("stock_id <", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdLessThanOrEqualTo(Integer value) {
            addCriterion("stock_id <=", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdIn(List<Integer> values) {
            addCriterion("stock_id in", values, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdNotIn(List<Integer> values) {
            addCriterion("stock_id not in", values, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdBetween(Integer value1, Integer value2) {
            addCriterion("stock_id between", value1, value2, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdNotBetween(Integer value1, Integer value2) {
            addCriterion("stock_id not between", value1, value2, "stockId");
            return (Criteria) this;
        }

        public Criteria andCompanyFullnameIsNull() {
            addCriterion("company_fullname is null");
            return (Criteria) this;
        }

        public Criteria andCompanyFullnameIsNotNull() {
            addCriterion("company_fullname is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyFullnameEqualTo(String value) {
            addCriterion("company_fullname =", value, "companyFullname");
            return (Criteria) this;
        }

        public Criteria andCompanyFullnameNotEqualTo(String value) {
            addCriterion("company_fullname <>", value, "companyFullname");
            return (Criteria) this;
        }

        public Criteria andCompanyFullnameGreaterThan(String value) {
            addCriterion("company_fullname >", value, "companyFullname");
            return (Criteria) this;
        }

        public Criteria andCompanyFullnameGreaterThanOrEqualTo(String value) {
            addCriterion("company_fullname >=", value, "companyFullname");
            return (Criteria) this;
        }

        public Criteria andCompanyFullnameLessThan(String value) {
            addCriterion("company_fullname <", value, "companyFullname");
            return (Criteria) this;
        }

        public Criteria andCompanyFullnameLessThanOrEqualTo(String value) {
            addCriterion("company_fullname <=", value, "companyFullname");
            return (Criteria) this;
        }

        public Criteria andCompanyFullnameLike(String value) {
            addCriterion("company_fullname like", value, "companyFullname");
            return (Criteria) this;
        }

        public Criteria andCompanyFullnameNotLike(String value) {
            addCriterion("company_fullname not like", value, "companyFullname");
            return (Criteria) this;
        }

        public Criteria andCompanyFullnameIn(List<String> values) {
            addCriterion("company_fullname in", values, "companyFullname");
            return (Criteria) this;
        }

        public Criteria andCompanyFullnameNotIn(List<String> values) {
            addCriterion("company_fullname not in", values, "companyFullname");
            return (Criteria) this;
        }

        public Criteria andCompanyFullnameBetween(String value1, String value2) {
            addCriterion("company_fullname between", value1, value2, "companyFullname");
            return (Criteria) this;
        }

        public Criteria andCompanyFullnameNotBetween(String value1, String value2) {
            addCriterion("company_fullname not between", value1, value2, "companyFullname");
            return (Criteria) this;
        }

        public Criteria andListedDateIsNull() {
            addCriterion("listed_date is null");
            return (Criteria) this;
        }

        public Criteria andListedDateIsNotNull() {
            addCriterion("listed_date is not null");
            return (Criteria) this;
        }

        public Criteria andListedDateEqualTo(Date value) {
            addCriterionForJDBCDate("listed_date =", value, "listedDate");
            return (Criteria) this;
        }

        public Criteria andListedDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("listed_date <>", value, "listedDate");
            return (Criteria) this;
        }

        public Criteria andListedDateGreaterThan(Date value) {
            addCriterionForJDBCDate("listed_date >", value, "listedDate");
            return (Criteria) this;
        }

        public Criteria andListedDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("listed_date >=", value, "listedDate");
            return (Criteria) this;
        }

        public Criteria andListedDateLessThan(Date value) {
            addCriterionForJDBCDate("listed_date <", value, "listedDate");
            return (Criteria) this;
        }

        public Criteria andListedDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("listed_date <=", value, "listedDate");
            return (Criteria) this;
        }

        public Criteria andListedDateIn(List<Date> values) {
            addCriterionForJDBCDate("listed_date in", values, "listedDate");
            return (Criteria) this;
        }

        public Criteria andListedDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("listed_date not in", values, "listedDate");
            return (Criteria) this;
        }

        public Criteria andListedDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("listed_date between", value1, value2, "listedDate");
            return (Criteria) this;
        }

        public Criteria andListedDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("listed_date not between", value1, value2, "listedDate");
            return (Criteria) this;
        }

        public Criteria andGeneralCapitalIsNull() {
            addCriterion("general_capital is null");
            return (Criteria) this;
        }

        public Criteria andGeneralCapitalIsNotNull() {
            addCriterion("general_capital is not null");
            return (Criteria) this;
        }

        public Criteria andGeneralCapitalEqualTo(Long value) {
            addCriterion("general_capital =", value, "generalCapital");
            return (Criteria) this;
        }

        public Criteria andGeneralCapitalNotEqualTo(Long value) {
            addCriterion("general_capital <>", value, "generalCapital");
            return (Criteria) this;
        }

        public Criteria andGeneralCapitalGreaterThan(Long value) {
            addCriterion("general_capital >", value, "generalCapital");
            return (Criteria) this;
        }

        public Criteria andGeneralCapitalGreaterThanOrEqualTo(Long value) {
            addCriterion("general_capital >=", value, "generalCapital");
            return (Criteria) this;
        }

        public Criteria andGeneralCapitalLessThan(Long value) {
            addCriterion("general_capital <", value, "generalCapital");
            return (Criteria) this;
        }

        public Criteria andGeneralCapitalLessThanOrEqualTo(Long value) {
            addCriterion("general_capital <=", value, "generalCapital");
            return (Criteria) this;
        }

        public Criteria andGeneralCapitalIn(List<Long> values) {
            addCriterion("general_capital in", values, "generalCapital");
            return (Criteria) this;
        }

        public Criteria andGeneralCapitalNotIn(List<Long> values) {
            addCriterion("general_capital not in", values, "generalCapital");
            return (Criteria) this;
        }

        public Criteria andGeneralCapitalBetween(Long value1, Long value2) {
            addCriterion("general_capital between", value1, value2, "generalCapital");
            return (Criteria) this;
        }

        public Criteria andGeneralCapitalNotBetween(Long value1, Long value2) {
            addCriterion("general_capital not between", value1, value2, "generalCapital");
            return (Criteria) this;
        }

        public Criteria andCirculationCapitalIsNull() {
            addCriterion("circulation_capital is null");
            return (Criteria) this;
        }

        public Criteria andCirculationCapitalIsNotNull() {
            addCriterion("circulation_capital is not null");
            return (Criteria) this;
        }

        public Criteria andCirculationCapitalEqualTo(Long value) {
            addCriterion("circulation_capital =", value, "circulationCapital");
            return (Criteria) this;
        }

        public Criteria andCirculationCapitalNotEqualTo(Long value) {
            addCriterion("circulation_capital <>", value, "circulationCapital");
            return (Criteria) this;
        }

        public Criteria andCirculationCapitalGreaterThan(Long value) {
            addCriterion("circulation_capital >", value, "circulationCapital");
            return (Criteria) this;
        }

        public Criteria andCirculationCapitalGreaterThanOrEqualTo(Long value) {
            addCriterion("circulation_capital >=", value, "circulationCapital");
            return (Criteria) this;
        }

        public Criteria andCirculationCapitalLessThan(Long value) {
            addCriterion("circulation_capital <", value, "circulationCapital");
            return (Criteria) this;
        }

        public Criteria andCirculationCapitalLessThanOrEqualTo(Long value) {
            addCriterion("circulation_capital <=", value, "circulationCapital");
            return (Criteria) this;
        }

        public Criteria andCirculationCapitalIn(List<Long> values) {
            addCriterion("circulation_capital in", values, "circulationCapital");
            return (Criteria) this;
        }

        public Criteria andCirculationCapitalNotIn(List<Long> values) {
            addCriterion("circulation_capital not in", values, "circulationCapital");
            return (Criteria) this;
        }

        public Criteria andCirculationCapitalBetween(Long value1, Long value2) {
            addCriterion("circulation_capital between", value1, value2, "circulationCapital");
            return (Criteria) this;
        }

        public Criteria andCirculationCapitalNotBetween(Long value1, Long value2) {
            addCriterion("circulation_capital not between", value1, value2, "circulationCapital");
            return (Criteria) this;
        }

        public Criteria andRegionIsNull() {
            addCriterion("region is null");
            return (Criteria) this;
        }

        public Criteria andRegionIsNotNull() {
            addCriterion("region is not null");
            return (Criteria) this;
        }

        public Criteria andRegionEqualTo(String value) {
            addCriterion("region =", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotEqualTo(String value) {
            addCriterion("region <>", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThan(String value) {
            addCriterion("region >", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThanOrEqualTo(String value) {
            addCriterion("region >=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThan(String value) {
            addCriterion("region <", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThanOrEqualTo(String value) {
            addCriterion("region <=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLike(String value) {
            addCriterion("region like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotLike(String value) {
            addCriterion("region not like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionIn(List<String> values) {
            addCriterion("region in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotIn(List<String> values) {
            addCriterion("region not in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionBetween(String value1, String value2) {
            addCriterion("region between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotBetween(String value1, String value2) {
            addCriterion("region not between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andIndustryIsNull() {
            addCriterion("industry is null");
            return (Criteria) this;
        }

        public Criteria andIndustryIsNotNull() {
            addCriterion("industry is not null");
            return (Criteria) this;
        }

        public Criteria andIndustryEqualTo(String value) {
            addCriterion("industry =", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotEqualTo(String value) {
            addCriterion("industry <>", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryGreaterThan(String value) {
            addCriterion("industry >", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryGreaterThanOrEqualTo(String value) {
            addCriterion("industry >=", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryLessThan(String value) {
            addCriterion("industry <", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryLessThanOrEqualTo(String value) {
            addCriterion("industry <=", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryLike(String value) {
            addCriterion("industry like", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotLike(String value) {
            addCriterion("industry not like", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryIn(List<String> values) {
            addCriterion("industry in", values, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotIn(List<String> values) {
            addCriterion("industry not in", values, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryBetween(String value1, String value2) {
            addCriterion("industry between", value1, value2, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotBetween(String value1, String value2) {
            addCriterion("industry not between", value1, value2, "industry");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteIsNull() {
            addCriterion("company_website is null");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteIsNotNull() {
            addCriterion("company_website is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteEqualTo(String value) {
            addCriterion("company_website =", value, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteNotEqualTo(String value) {
            addCriterion("company_website <>", value, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteGreaterThan(String value) {
            addCriterion("company_website >", value, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteGreaterThanOrEqualTo(String value) {
            addCriterion("company_website >=", value, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteLessThan(String value) {
            addCriterion("company_website <", value, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteLessThanOrEqualTo(String value) {
            addCriterion("company_website <=", value, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteLike(String value) {
            addCriterion("company_website like", value, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteNotLike(String value) {
            addCriterion("company_website not like", value, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteIn(List<String> values) {
            addCriterion("company_website in", values, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteNotIn(List<String> values) {
            addCriterion("company_website not in", values, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteBetween(String value1, String value2) {
            addCriterion("company_website between", value1, value2, "companyWebsite");
            return (Criteria) this;
        }

        public Criteria andCompanyWebsiteNotBetween(String value1, String value2) {
            addCriterion("company_website not between", value1, value2, "companyWebsite");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_extend_info
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 17 15:15:42 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}