package com.mybatis.model;

public class StockCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_category.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_category.block_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private String blockCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_category.child_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private String childCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_category.category_name
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_category.category_code
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private String categoryCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public StockCategory(Integer id, String blockCategory, String childCategory, String categoryName, String categoryCode) {
        this.id = id;
        this.blockCategory = blockCategory;
        this.childCategory = childCategory;
        this.categoryName = categoryName;
        this.categoryCode = categoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public StockCategory() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_category.id
     *
     * @return the value of stock_category.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_category.id
     *
     * @param id the value for stock_category.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_category.block_category
     *
     * @return the value of stock_category.block_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getBlockCategory() {
        return blockCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_category.block_category
     *
     * @param blockCategory the value for stock_category.block_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setBlockCategory(String blockCategory) {
        this.blockCategory = blockCategory == null ? null : blockCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_category.child_category
     *
     * @return the value of stock_category.child_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getChildCategory() {
        return childCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_category.child_category
     *
     * @param childCategory the value for stock_category.child_category
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setChildCategory(String childCategory) {
        this.childCategory = childCategory == null ? null : childCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_category.category_name
     *
     * @return the value of stock_category.category_name
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_category.category_name
     *
     * @param categoryName the value for stock_category.category_name
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_category.category_code
     *
     * @return the value of stock_category.category_code
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_category.category_code
     *
     * @param categoryCode the value for stock_category.category_code
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode == null ? null : categoryCode.trim();
    }
}