package com.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class StockMa {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockma.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockma.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockma.stock_date
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Date stockDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockma.ma5
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private BigDecimal ma5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockma.ma10
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private BigDecimal ma10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockma.ma20
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private BigDecimal ma20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockma.ma30
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private BigDecimal ma30;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockma.ma60
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private BigDecimal ma60;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockma.ma120
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private BigDecimal ma120;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockma.ma20_raisedays
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer ma20Raisedays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockma.ma20_dropdays
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer ma20Dropdays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockma.ma30_raisedays
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer ma30Raisedays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockma.ma30_dropdays
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer ma30Dropdays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockma.stock_history_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer stockHistoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public StockMa(Integer id, Integer stockId, Date stockDate, BigDecimal ma5, BigDecimal ma10, BigDecimal ma20, BigDecimal ma30, BigDecimal ma60, BigDecimal ma120, Integer ma20Raisedays, Integer ma20Dropdays, Integer ma30Raisedays, Integer ma30Dropdays, Integer stockHistoryId) {
        this.id = id;
        this.stockId = stockId;
        this.stockDate = stockDate;
        this.ma5 = ma5;
        this.ma10 = ma10;
        this.ma20 = ma20;
        this.ma30 = ma30;
        this.ma60 = ma60;
        this.ma120 = ma120;
        this.ma20Raisedays = ma20Raisedays;
        this.ma20Dropdays = ma20Dropdays;
        this.ma30Raisedays = ma30Raisedays;
        this.ma30Dropdays = ma30Dropdays;
        this.stockHistoryId = stockHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public StockMa() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockma.id
     *
     * @return the value of stockma.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockma.id
     *
     * @param id the value for stockma.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockma.stock_id
     *
     * @return the value of stockma.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockma.stock_id
     *
     * @param stockId the value for stockma.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockma.stock_date
     *
     * @return the value of stockma.stock_date
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Date getStockDate() {
        return stockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockma.stock_date
     *
     * @param stockDate the value for stockma.stock_date
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setStockDate(Date stockDate) {
        this.stockDate = stockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockma.ma5
     *
     * @return the value of stockma.ma5
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public BigDecimal getMa5() {
        return ma5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockma.ma5
     *
     * @param ma5 the value for stockma.ma5
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setMa5(BigDecimal ma5) {
        this.ma5 = ma5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockma.ma10
     *
     * @return the value of stockma.ma10
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public BigDecimal getMa10() {
        return ma10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockma.ma10
     *
     * @param ma10 the value for stockma.ma10
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setMa10(BigDecimal ma10) {
        this.ma10 = ma10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockma.ma20
     *
     * @return the value of stockma.ma20
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public BigDecimal getMa20() {
        return ma20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockma.ma20
     *
     * @param ma20 the value for stockma.ma20
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setMa20(BigDecimal ma20) {
        this.ma20 = ma20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockma.ma30
     *
     * @return the value of stockma.ma30
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public BigDecimal getMa30() {
        return ma30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockma.ma30
     *
     * @param ma30 the value for stockma.ma30
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setMa30(BigDecimal ma30) {
        this.ma30 = ma30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockma.ma60
     *
     * @return the value of stockma.ma60
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public BigDecimal getMa60() {
        return ma60;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockma.ma60
     *
     * @param ma60 the value for stockma.ma60
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setMa60(BigDecimal ma60) {
        this.ma60 = ma60;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockma.ma120
     *
     * @return the value of stockma.ma120
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public BigDecimal getMa120() {
        return ma120;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockma.ma120
     *
     * @param ma120 the value for stockma.ma120
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setMa120(BigDecimal ma120) {
        this.ma120 = ma120;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockma.ma20_raisedays
     *
     * @return the value of stockma.ma20_raisedays
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getMa20Raisedays() {
        return ma20Raisedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockma.ma20_raisedays
     *
     * @param ma20Raisedays the value for stockma.ma20_raisedays
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setMa20Raisedays(Integer ma20Raisedays) {
        this.ma20Raisedays = ma20Raisedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockma.ma20_dropdays
     *
     * @return the value of stockma.ma20_dropdays
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getMa20Dropdays() {
        return ma20Dropdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockma.ma20_dropdays
     *
     * @param ma20Dropdays the value for stockma.ma20_dropdays
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setMa20Dropdays(Integer ma20Dropdays) {
        this.ma20Dropdays = ma20Dropdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockma.ma30_raisedays
     *
     * @return the value of stockma.ma30_raisedays
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getMa30Raisedays() {
        return ma30Raisedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockma.ma30_raisedays
     *
     * @param ma30Raisedays the value for stockma.ma30_raisedays
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setMa30Raisedays(Integer ma30Raisedays) {
        this.ma30Raisedays = ma30Raisedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockma.ma30_dropdays
     *
     * @return the value of stockma.ma30_dropdays
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getMa30Dropdays() {
        return ma30Dropdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockma.ma30_dropdays
     *
     * @param ma30Dropdays the value for stockma.ma30_dropdays
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setMa30Dropdays(Integer ma30Dropdays) {
        this.ma30Dropdays = ma30Dropdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockma.stock_history_id
     *
     * @return the value of stockma.stock_history_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getStockHistoryId() {
        return stockHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockma.stock_history_id
     *
     * @param stockHistoryId the value for stockma.stock_history_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setStockHistoryId(Integer stockHistoryId) {
        this.stockHistoryId = stockHistoryId;
    }

    @Override
    public String toString() {
    		return "StockId: " + stockId + "; StockDate: " + stockDate.toString() + "; StockHistoryId: " + stockHistoryId + "; Ma20Raise: " + ma20Raisedays 
    				+ "; Ma20Drop: " + ma20Dropdays + "; Ma30Raise: " + ma30Raisedays + "; Ma30Drop: " + ma30Dropdays; 
    }
}