package com.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class StockMaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public StockMaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStockIdIsNull() {
            addCriterion("stock_id is null");
            return (Criteria) this;
        }

        public Criteria andStockIdIsNotNull() {
            addCriterion("stock_id is not null");
            return (Criteria) this;
        }

        public Criteria andStockIdEqualTo(Integer value) {
            addCriterion("stock_id =", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdNotEqualTo(Integer value) {
            addCriterion("stock_id <>", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdGreaterThan(Integer value) {
            addCriterion("stock_id >", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("stock_id >=", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdLessThan(Integer value) {
            addCriterion("stock_id <", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdLessThanOrEqualTo(Integer value) {
            addCriterion("stock_id <=", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdIn(List<Integer> values) {
            addCriterion("stock_id in", values, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdNotIn(List<Integer> values) {
            addCriterion("stock_id not in", values, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdBetween(Integer value1, Integer value2) {
            addCriterion("stock_id between", value1, value2, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdNotBetween(Integer value1, Integer value2) {
            addCriterion("stock_id not between", value1, value2, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockDateIsNull() {
            addCriterion("stock_date is null");
            return (Criteria) this;
        }

        public Criteria andStockDateIsNotNull() {
            addCriterion("stock_date is not null");
            return (Criteria) this;
        }

        public Criteria andStockDateEqualTo(Date value) {
            addCriterionForJDBCDate("stock_date =", value, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("stock_date <>", value, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateGreaterThan(Date value) {
            addCriterionForJDBCDate("stock_date >", value, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("stock_date >=", value, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateLessThan(Date value) {
            addCriterionForJDBCDate("stock_date <", value, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("stock_date <=", value, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateIn(List<Date> values) {
            addCriterionForJDBCDate("stock_date in", values, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("stock_date not in", values, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("stock_date between", value1, value2, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("stock_date not between", value1, value2, "stockDate");
            return (Criteria) this;
        }

        public Criteria andMa5IsNull() {
            addCriterion("ma5 is null");
            return (Criteria) this;
        }

        public Criteria andMa5IsNotNull() {
            addCriterion("ma5 is not null");
            return (Criteria) this;
        }

        public Criteria andMa5EqualTo(BigDecimal value) {
            addCriterion("ma5 =", value, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5NotEqualTo(BigDecimal value) {
            addCriterion("ma5 <>", value, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5GreaterThan(BigDecimal value) {
            addCriterion("ma5 >", value, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ma5 >=", value, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5LessThan(BigDecimal value) {
            addCriterion("ma5 <", value, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5LessThanOrEqualTo(BigDecimal value) {
            addCriterion("ma5 <=", value, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5In(List<BigDecimal> values) {
            addCriterion("ma5 in", values, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5NotIn(List<BigDecimal> values) {
            addCriterion("ma5 not in", values, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("ma5 between", value1, value2, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ma5 not between", value1, value2, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa10IsNull() {
            addCriterion("ma10 is null");
            return (Criteria) this;
        }

        public Criteria andMa10IsNotNull() {
            addCriterion("ma10 is not null");
            return (Criteria) this;
        }

        public Criteria andMa10EqualTo(BigDecimal value) {
            addCriterion("ma10 =", value, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10NotEqualTo(BigDecimal value) {
            addCriterion("ma10 <>", value, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10GreaterThan(BigDecimal value) {
            addCriterion("ma10 >", value, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ma10 >=", value, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10LessThan(BigDecimal value) {
            addCriterion("ma10 <", value, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10LessThanOrEqualTo(BigDecimal value) {
            addCriterion("ma10 <=", value, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10In(List<BigDecimal> values) {
            addCriterion("ma10 in", values, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10NotIn(List<BigDecimal> values) {
            addCriterion("ma10 not in", values, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("ma10 between", value1, value2, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ma10 not between", value1, value2, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa20IsNull() {
            addCriterion("ma20 is null");
            return (Criteria) this;
        }

        public Criteria andMa20IsNotNull() {
            addCriterion("ma20 is not null");
            return (Criteria) this;
        }

        public Criteria andMa20EqualTo(BigDecimal value) {
            addCriterion("ma20 =", value, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20NotEqualTo(BigDecimal value) {
            addCriterion("ma20 <>", value, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20GreaterThan(BigDecimal value) {
            addCriterion("ma20 >", value, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ma20 >=", value, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20LessThan(BigDecimal value) {
            addCriterion("ma20 <", value, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20LessThanOrEqualTo(BigDecimal value) {
            addCriterion("ma20 <=", value, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20In(List<BigDecimal> values) {
            addCriterion("ma20 in", values, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20NotIn(List<BigDecimal> values) {
            addCriterion("ma20 not in", values, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("ma20 between", value1, value2, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ma20 not between", value1, value2, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa30IsNull() {
            addCriterion("ma30 is null");
            return (Criteria) this;
        }

        public Criteria andMa30IsNotNull() {
            addCriterion("ma30 is not null");
            return (Criteria) this;
        }

        public Criteria andMa30EqualTo(BigDecimal value) {
            addCriterion("ma30 =", value, "ma30");
            return (Criteria) this;
        }

        public Criteria andMa30NotEqualTo(BigDecimal value) {
            addCriterion("ma30 <>", value, "ma30");
            return (Criteria) this;
        }

        public Criteria andMa30GreaterThan(BigDecimal value) {
            addCriterion("ma30 >", value, "ma30");
            return (Criteria) this;
        }

        public Criteria andMa30GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ma30 >=", value, "ma30");
            return (Criteria) this;
        }

        public Criteria andMa30LessThan(BigDecimal value) {
            addCriterion("ma30 <", value, "ma30");
            return (Criteria) this;
        }

        public Criteria andMa30LessThanOrEqualTo(BigDecimal value) {
            addCriterion("ma30 <=", value, "ma30");
            return (Criteria) this;
        }

        public Criteria andMa30In(List<BigDecimal> values) {
            addCriterion("ma30 in", values, "ma30");
            return (Criteria) this;
        }

        public Criteria andMa30NotIn(List<BigDecimal> values) {
            addCriterion("ma30 not in", values, "ma30");
            return (Criteria) this;
        }

        public Criteria andMa30Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("ma30 between", value1, value2, "ma30");
            return (Criteria) this;
        }

        public Criteria andMa30NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ma30 not between", value1, value2, "ma30");
            return (Criteria) this;
        }

        public Criteria andMa60IsNull() {
            addCriterion("ma60 is null");
            return (Criteria) this;
        }

        public Criteria andMa60IsNotNull() {
            addCriterion("ma60 is not null");
            return (Criteria) this;
        }

        public Criteria andMa60EqualTo(BigDecimal value) {
            addCriterion("ma60 =", value, "ma60");
            return (Criteria) this;
        }

        public Criteria andMa60NotEqualTo(BigDecimal value) {
            addCriterion("ma60 <>", value, "ma60");
            return (Criteria) this;
        }

        public Criteria andMa60GreaterThan(BigDecimal value) {
            addCriterion("ma60 >", value, "ma60");
            return (Criteria) this;
        }

        public Criteria andMa60GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ma60 >=", value, "ma60");
            return (Criteria) this;
        }

        public Criteria andMa60LessThan(BigDecimal value) {
            addCriterion("ma60 <", value, "ma60");
            return (Criteria) this;
        }

        public Criteria andMa60LessThanOrEqualTo(BigDecimal value) {
            addCriterion("ma60 <=", value, "ma60");
            return (Criteria) this;
        }

        public Criteria andMa60In(List<BigDecimal> values) {
            addCriterion("ma60 in", values, "ma60");
            return (Criteria) this;
        }

        public Criteria andMa60NotIn(List<BigDecimal> values) {
            addCriterion("ma60 not in", values, "ma60");
            return (Criteria) this;
        }

        public Criteria andMa60Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("ma60 between", value1, value2, "ma60");
            return (Criteria) this;
        }

        public Criteria andMa60NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ma60 not between", value1, value2, "ma60");
            return (Criteria) this;
        }

        public Criteria andMa120IsNull() {
            addCriterion("ma120 is null");
            return (Criteria) this;
        }

        public Criteria andMa120IsNotNull() {
            addCriterion("ma120 is not null");
            return (Criteria) this;
        }

        public Criteria andMa120EqualTo(BigDecimal value) {
            addCriterion("ma120 =", value, "ma120");
            return (Criteria) this;
        }

        public Criteria andMa120NotEqualTo(BigDecimal value) {
            addCriterion("ma120 <>", value, "ma120");
            return (Criteria) this;
        }

        public Criteria andMa120GreaterThan(BigDecimal value) {
            addCriterion("ma120 >", value, "ma120");
            return (Criteria) this;
        }

        public Criteria andMa120GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ma120 >=", value, "ma120");
            return (Criteria) this;
        }

        public Criteria andMa120LessThan(BigDecimal value) {
            addCriterion("ma120 <", value, "ma120");
            return (Criteria) this;
        }

        public Criteria andMa120LessThanOrEqualTo(BigDecimal value) {
            addCriterion("ma120 <=", value, "ma120");
            return (Criteria) this;
        }

        public Criteria andMa120In(List<BigDecimal> values) {
            addCriterion("ma120 in", values, "ma120");
            return (Criteria) this;
        }

        public Criteria andMa120NotIn(List<BigDecimal> values) {
            addCriterion("ma120 not in", values, "ma120");
            return (Criteria) this;
        }

        public Criteria andMa120Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("ma120 between", value1, value2, "ma120");
            return (Criteria) this;
        }

        public Criteria andMa120NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ma120 not between", value1, value2, "ma120");
            return (Criteria) this;
        }

        public Criteria andMa20RaisedaysIsNull() {
            addCriterion("ma20_raisedays is null");
            return (Criteria) this;
        }

        public Criteria andMa20RaisedaysIsNotNull() {
            addCriterion("ma20_raisedays is not null");
            return (Criteria) this;
        }

        public Criteria andMa20RaisedaysEqualTo(Integer value) {
            addCriterion("ma20_raisedays =", value, "ma20Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa20RaisedaysNotEqualTo(Integer value) {
            addCriterion("ma20_raisedays <>", value, "ma20Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa20RaisedaysGreaterThan(Integer value) {
            addCriterion("ma20_raisedays >", value, "ma20Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa20RaisedaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("ma20_raisedays >=", value, "ma20Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa20RaisedaysLessThan(Integer value) {
            addCriterion("ma20_raisedays <", value, "ma20Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa20RaisedaysLessThanOrEqualTo(Integer value) {
            addCriterion("ma20_raisedays <=", value, "ma20Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa20RaisedaysIn(List<Integer> values) {
            addCriterion("ma20_raisedays in", values, "ma20Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa20RaisedaysNotIn(List<Integer> values) {
            addCriterion("ma20_raisedays not in", values, "ma20Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa20RaisedaysBetween(Integer value1, Integer value2) {
            addCriterion("ma20_raisedays between", value1, value2, "ma20Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa20RaisedaysNotBetween(Integer value1, Integer value2) {
            addCriterion("ma20_raisedays not between", value1, value2, "ma20Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa20DropdaysIsNull() {
            addCriterion("ma20_dropdays is null");
            return (Criteria) this;
        }

        public Criteria andMa20DropdaysIsNotNull() {
            addCriterion("ma20_dropdays is not null");
            return (Criteria) this;
        }

        public Criteria andMa20DropdaysEqualTo(Integer value) {
            addCriterion("ma20_dropdays =", value, "ma20Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa20DropdaysNotEqualTo(Integer value) {
            addCriterion("ma20_dropdays <>", value, "ma20Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa20DropdaysGreaterThan(Integer value) {
            addCriterion("ma20_dropdays >", value, "ma20Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa20DropdaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("ma20_dropdays >=", value, "ma20Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa20DropdaysLessThan(Integer value) {
            addCriterion("ma20_dropdays <", value, "ma20Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa20DropdaysLessThanOrEqualTo(Integer value) {
            addCriterion("ma20_dropdays <=", value, "ma20Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa20DropdaysIn(List<Integer> values) {
            addCriterion("ma20_dropdays in", values, "ma20Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa20DropdaysNotIn(List<Integer> values) {
            addCriterion("ma20_dropdays not in", values, "ma20Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa20DropdaysBetween(Integer value1, Integer value2) {
            addCriterion("ma20_dropdays between", value1, value2, "ma20Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa20DropdaysNotBetween(Integer value1, Integer value2) {
            addCriterion("ma20_dropdays not between", value1, value2, "ma20Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa30RaisedaysIsNull() {
            addCriterion("ma30_raisedays is null");
            return (Criteria) this;
        }

        public Criteria andMa30RaisedaysIsNotNull() {
            addCriterion("ma30_raisedays is not null");
            return (Criteria) this;
        }

        public Criteria andMa30RaisedaysEqualTo(Integer value) {
            addCriterion("ma30_raisedays =", value, "ma30Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa30RaisedaysNotEqualTo(Integer value) {
            addCriterion("ma30_raisedays <>", value, "ma30Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa30RaisedaysGreaterThan(Integer value) {
            addCriterion("ma30_raisedays >", value, "ma30Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa30RaisedaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("ma30_raisedays >=", value, "ma30Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa30RaisedaysLessThan(Integer value) {
            addCriterion("ma30_raisedays <", value, "ma30Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa30RaisedaysLessThanOrEqualTo(Integer value) {
            addCriterion("ma30_raisedays <=", value, "ma30Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa30RaisedaysIn(List<Integer> values) {
            addCriterion("ma30_raisedays in", values, "ma30Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa30RaisedaysNotIn(List<Integer> values) {
            addCriterion("ma30_raisedays not in", values, "ma30Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa30RaisedaysBetween(Integer value1, Integer value2) {
            addCriterion("ma30_raisedays between", value1, value2, "ma30Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa30RaisedaysNotBetween(Integer value1, Integer value2) {
            addCriterion("ma30_raisedays not between", value1, value2, "ma30Raisedays");
            return (Criteria) this;
        }

        public Criteria andMa30DropdaysIsNull() {
            addCriterion("ma30_dropdays is null");
            return (Criteria) this;
        }

        public Criteria andMa30DropdaysIsNotNull() {
            addCriterion("ma30_dropdays is not null");
            return (Criteria) this;
        }

        public Criteria andMa30DropdaysEqualTo(Integer value) {
            addCriterion("ma30_dropdays =", value, "ma30Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa30DropdaysNotEqualTo(Integer value) {
            addCriterion("ma30_dropdays <>", value, "ma30Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa30DropdaysGreaterThan(Integer value) {
            addCriterion("ma30_dropdays >", value, "ma30Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa30DropdaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("ma30_dropdays >=", value, "ma30Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa30DropdaysLessThan(Integer value) {
            addCriterion("ma30_dropdays <", value, "ma30Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa30DropdaysLessThanOrEqualTo(Integer value) {
            addCriterion("ma30_dropdays <=", value, "ma30Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa30DropdaysIn(List<Integer> values) {
            addCriterion("ma30_dropdays in", values, "ma30Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa30DropdaysNotIn(List<Integer> values) {
            addCriterion("ma30_dropdays not in", values, "ma30Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa30DropdaysBetween(Integer value1, Integer value2) {
            addCriterion("ma30_dropdays between", value1, value2, "ma30Dropdays");
            return (Criteria) this;
        }

        public Criteria andMa30DropdaysNotBetween(Integer value1, Integer value2) {
            addCriterion("ma30_dropdays not between", value1, value2, "ma30Dropdays");
            return (Criteria) this;
        }

        public Criteria andStockHistoryIdIsNull() {
            addCriterion("stock_history_id is null");
            return (Criteria) this;
        }

        public Criteria andStockHistoryIdIsNotNull() {
            addCriterion("stock_history_id is not null");
            return (Criteria) this;
        }

        public Criteria andStockHistoryIdEqualTo(Integer value) {
            addCriterion("stock_history_id =", value, "stockHistoryId");
            return (Criteria) this;
        }

        public Criteria andStockHistoryIdNotEqualTo(Integer value) {
            addCriterion("stock_history_id <>", value, "stockHistoryId");
            return (Criteria) this;
        }

        public Criteria andStockHistoryIdGreaterThan(Integer value) {
            addCriterion("stock_history_id >", value, "stockHistoryId");
            return (Criteria) this;
        }

        public Criteria andStockHistoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("stock_history_id >=", value, "stockHistoryId");
            return (Criteria) this;
        }

        public Criteria andStockHistoryIdLessThan(Integer value) {
            addCriterion("stock_history_id <", value, "stockHistoryId");
            return (Criteria) this;
        }

        public Criteria andStockHistoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("stock_history_id <=", value, "stockHistoryId");
            return (Criteria) this;
        }

        public Criteria andStockHistoryIdIn(List<Integer> values) {
            addCriterion("stock_history_id in", values, "stockHistoryId");
            return (Criteria) this;
        }

        public Criteria andStockHistoryIdNotIn(List<Integer> values) {
            addCriterion("stock_history_id not in", values, "stockHistoryId");
            return (Criteria) this;
        }

        public Criteria andStockHistoryIdBetween(Integer value1, Integer value2) {
            addCriterion("stock_history_id between", value1, value2, "stockHistoryId");
            return (Criteria) this;
        }

        public Criteria andStockHistoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("stock_history_id not between", value1, value2, "stockHistoryId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stockma
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 17 15:15:42 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stockma
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}