package com.mybatis.model;

import java.util.Date;

public class StockExtendInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_extend_info.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_extend_info.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_extend_info.company_fullname
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private String companyFullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_extend_info.listed_date
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Date listedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_extend_info.general_capital
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Long generalCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_extend_info.circulation_capital
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Long circulationCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_extend_info.region
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_extend_info.province
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_extend_info.city
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_extend_info.industry
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_extend_info.company_website
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private String companyWebsite;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public StockExtendInfo(Integer id, Integer stockId, String companyFullname, Date listedDate, Long generalCapital, Long circulationCapital, String region, String province, String city, String industry, String companyWebsite) {
        this.id = id;
        this.stockId = stockId;
        this.companyFullname = companyFullname;
        this.listedDate = listedDate;
        this.generalCapital = generalCapital;
        this.circulationCapital = circulationCapital;
        this.region = region;
        this.province = province;
        this.city = city;
        this.industry = industry;
        this.companyWebsite = companyWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_extend_info
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public StockExtendInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_extend_info.id
     *
     * @return the value of stock_extend_info.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_extend_info.id
     *
     * @param id the value for stock_extend_info.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_extend_info.stock_id
     *
     * @return the value of stock_extend_info.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_extend_info.stock_id
     *
     * @param stockId the value for stock_extend_info.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_extend_info.company_fullname
     *
     * @return the value of stock_extend_info.company_fullname
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getCompanyFullname() {
        return companyFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_extend_info.company_fullname
     *
     * @param companyFullname the value for stock_extend_info.company_fullname
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setCompanyFullname(String companyFullname) {
        this.companyFullname = companyFullname == null ? null : companyFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_extend_info.listed_date
     *
     * @return the value of stock_extend_info.listed_date
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Date getListedDate() {
        return listedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_extend_info.listed_date
     *
     * @param listedDate the value for stock_extend_info.listed_date
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setListedDate(Date listedDate) {
        this.listedDate = listedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_extend_info.general_capital
     *
     * @return the value of stock_extend_info.general_capital
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Long getGeneralCapital() {
        return generalCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_extend_info.general_capital
     *
     * @param generalCapital the value for stock_extend_info.general_capital
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setGeneralCapital(Long generalCapital) {
        this.generalCapital = generalCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_extend_info.circulation_capital
     *
     * @return the value of stock_extend_info.circulation_capital
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Long getCirculationCapital() {
        return circulationCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_extend_info.circulation_capital
     *
     * @param circulationCapital the value for stock_extend_info.circulation_capital
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setCirculationCapital(Long circulationCapital) {
        this.circulationCapital = circulationCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_extend_info.region
     *
     * @return the value of stock_extend_info.region
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_extend_info.region
     *
     * @param region the value for stock_extend_info.region
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_extend_info.province
     *
     * @return the value of stock_extend_info.province
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_extend_info.province
     *
     * @param province the value for stock_extend_info.province
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_extend_info.city
     *
     * @return the value of stock_extend_info.city
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_extend_info.city
     *
     * @param city the value for stock_extend_info.city
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_extend_info.industry
     *
     * @return the value of stock_extend_info.industry
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_extend_info.industry
     *
     * @param industry the value for stock_extend_info.industry
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_extend_info.company_website
     *
     * @return the value of stock_extend_info.company_website
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getCompanyWebsite() {
        return companyWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_extend_info.company_website
     *
     * @param companyWebsite the value for stock_extend_info.company_website
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setCompanyWebsite(String companyWebsite) {
        this.companyWebsite = companyWebsite == null ? null : companyWebsite.trim();
    }
}