package com.mybatis.model;

import java.util.Date;

public class StockTradingDate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trading_date.id
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trading_date.trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    private Date tradingDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    public StockTradingDate(Integer id, Date tradingDate) {
        this.id = id;
        this.tradingDate = tradingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    public StockTradingDate() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trading_date.id
     *
     * @return the value of stock_trading_date.id
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trading_date.id
     *
     * @param id the value for stock_trading_date.id
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trading_date.trading_date
     *
     * @return the value of stock_trading_date.trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    public Date getTradingDate() {
        return tradingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trading_date.trading_date
     *
     * @param tradingDate the value for stock_trading_date.trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:43 CST 2017
     */
    public void setTradingDate(Date tradingDate) {
        this.tradingDate = tradingDate;
    }
}