package com.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class StockHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.id
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.stock_id
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    private Integer stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.stock_day
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    private Date stockDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.open_price
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    private BigDecimal openPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.close_price
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    private BigDecimal closePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.min_price
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    private BigDecimal minPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.max_price
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    private BigDecimal maxPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.trade_num
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    private Long tradeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.trade_money
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    private BigDecimal tradeMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.turnover
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    private Float turnover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.swing
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    private Float swing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.diff_rate
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    private Float diffRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.trading_date
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    private Integer tradingDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public StockHistory(Integer id, Integer stockId, Date stockDay, BigDecimal openPrice, BigDecimal closePrice, BigDecimal minPrice, BigDecimal maxPrice, Long tradeNum, BigDecimal tradeMoney, Float turnover, Float swing, Float diffRate, Integer tradingDate) {
        this.id = id;
        this.stockId = stockId;
        this.stockDay = stockDay;
        this.openPrice = openPrice;
        this.closePrice = closePrice;
        this.minPrice = minPrice;
        this.maxPrice = maxPrice;
        this.tradeNum = tradeNum;
        this.tradeMoney = tradeMoney;
        this.turnover = turnover;
        this.swing = swing;
        this.diffRate = diffRate;
        this.tradingDate = tradingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public StockHistory() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.id
     *
     * @return the value of stock_history.id
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.id
     *
     * @param id the value for stock_history.id
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.stock_id
     *
     * @return the value of stock_history.stock_id
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.stock_id
     *
     * @param stockId the value for stock_history.stock_id
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.stock_day
     *
     * @return the value of stock_history.stock_day
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public Date getStockDay() {
        return stockDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.stock_day
     *
     * @param stockDay the value for stock_history.stock_day
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public void setStockDay(Date stockDay) {
        this.stockDay = stockDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.open_price
     *
     * @return the value of stock_history.open_price
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public BigDecimal getOpenPrice() {
        return openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.open_price
     *
     * @param openPrice the value for stock_history.open_price
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public void setOpenPrice(BigDecimal openPrice) {
        this.openPrice = openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.close_price
     *
     * @return the value of stock_history.close_price
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public BigDecimal getClosePrice() {
        return closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.close_price
     *
     * @param closePrice the value for stock_history.close_price
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public void setClosePrice(BigDecimal closePrice) {
        this.closePrice = closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.min_price
     *
     * @return the value of stock_history.min_price
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public BigDecimal getMinPrice() {
        return minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.min_price
     *
     * @param minPrice the value for stock_history.min_price
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public void setMinPrice(BigDecimal minPrice) {
        this.minPrice = minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.max_price
     *
     * @return the value of stock_history.max_price
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public BigDecimal getMaxPrice() {
        return maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.max_price
     *
     * @param maxPrice the value for stock_history.max_price
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public void setMaxPrice(BigDecimal maxPrice) {
        this.maxPrice = maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.trade_num
     *
     * @return the value of stock_history.trade_num
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public Long getTradeNum() {
        return tradeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.trade_num
     *
     * @param tradeNum the value for stock_history.trade_num
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public void setTradeNum(Long tradeNum) {
        this.tradeNum = tradeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.trade_money
     *
     * @return the value of stock_history.trade_money
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public BigDecimal getTradeMoney() {
        return tradeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.trade_money
     *
     * @param tradeMoney the value for stock_history.trade_money
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public void setTradeMoney(BigDecimal tradeMoney) {
        this.tradeMoney = tradeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.turnover
     *
     * @return the value of stock_history.turnover
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public Float getTurnover() {
        return turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.turnover
     *
     * @param turnover the value for stock_history.turnover
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public void setTurnover(Float turnover) {
        this.turnover = turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.swing
     *
     * @return the value of stock_history.swing
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public Float getSwing() {
        return swing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.swing
     *
     * @param swing the value for stock_history.swing
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public void setSwing(Float swing) {
        this.swing = swing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.diff_rate
     *
     * @return the value of stock_history.diff_rate
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public Float getDiffRate() {
        return diffRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.diff_rate
     *
     * @param diffRate the value for stock_history.diff_rate
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public void setDiffRate(Float diffRate) {
        this.diffRate = diffRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.trading_date
     *
     * @return the value of stock_history.trading_date
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public Integer getTradingDate() {
        return tradingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.trading_date
     *
     * @param tradingDate the value for stock_history.trading_date
     *
     * @mbggenerated Thu Oct 05 21:51:04 CST 2017
     */
    public void setTradingDate(Integer tradingDate) {
        this.tradingDate = tradingDate;
    }
}