package com.mybatis.model;

public class Stock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock_name
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private String stockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock_code
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private String stockCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.IsDelisted
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Boolean isdelisted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.pinyin
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private String pinyin;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Stock(Integer id, String stockName, String stockCode, Boolean isdelisted, String pinyin) {
        this.id = id;
        this.stockName = stockName;
        this.stockCode = stockCode;
        this.isdelisted = isdelisted;
        this.pinyin = pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Stock() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.id
     *
     * @return the value of stock.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.id
     *
     * @param id the value for stock.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stock_name
     *
     * @return the value of stock.stock_name
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stock_name
     *
     * @param stockName the value for stock.stock_name
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setStockName(String stockName) {
        this.stockName = stockName == null ? null : stockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stock_code
     *
     * @return the value of stock.stock_code
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stock_code
     *
     * @param stockCode the value for stock.stock_code
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.IsDelisted
     *
     * @return the value of stock.IsDelisted
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Boolean getIsdelisted() {
        return isdelisted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.IsDelisted
     *
     * @param isdelisted the value for stock.IsDelisted
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setIsdelisted(Boolean isdelisted) {
        this.isdelisted = isdelisted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.pinyin
     *
     * @return the value of stock.pinyin
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.pinyin
     *
     * @param pinyin the value for stock.pinyin
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }
}