package com.mybatis.model;

import java.util.Date;

public class StockKdj {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockkdj.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockkdj.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockkdj.stock_date
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Date stockDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockkdj.k
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Float k;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockkdj.d
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Float d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockkdj.j
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Float j;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockkdj.rsv
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Float rsv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockkdj.stock_history_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer stockHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockkdj.trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    private Integer tradingDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockkdj
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public StockKdj(Integer id, Integer stockId, Date stockDate, Float k, Float d, Float j, Float rsv, Integer stockHistoryId, Integer tradingDate) {
        this.id = id;
        this.stockId = stockId;
        this.stockDate = stockDate;
        this.k = k;
        this.d = d;
        this.j = j;
        this.rsv = rsv;
        this.stockHistoryId = stockHistoryId;
        this.tradingDate = tradingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockkdj
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public StockKdj() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockkdj.id
     *
     * @return the value of stockkdj.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockkdj.id
     *
     * @param id the value for stockkdj.id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockkdj.stock_id
     *
     * @return the value of stockkdj.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockkdj.stock_id
     *
     * @param stockId the value for stockkdj.stock_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockkdj.stock_date
     *
     * @return the value of stockkdj.stock_date
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Date getStockDate() {
        return stockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockkdj.stock_date
     *
     * @param stockDate the value for stockkdj.stock_date
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setStockDate(Date stockDate) {
        this.stockDate = stockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockkdj.k
     *
     * @return the value of stockkdj.k
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Float getK() {
        return k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockkdj.k
     *
     * @param k the value for stockkdj.k
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setK(Float k) {
        this.k = k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockkdj.d
     *
     * @return the value of stockkdj.d
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Float getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockkdj.d
     *
     * @param d the value for stockkdj.d
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setD(Float d) {
        this.d = d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockkdj.j
     *
     * @return the value of stockkdj.j
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Float getJ() {
        return j;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockkdj.j
     *
     * @param j the value for stockkdj.j
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setJ(Float j) {
        this.j = j;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockkdj.rsv
     *
     * @return the value of stockkdj.rsv
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Float getRsv() {
        return rsv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockkdj.rsv
     *
     * @param rsv the value for stockkdj.rsv
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setRsv(Float rsv) {
        this.rsv = rsv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockkdj.stock_history_id
     *
     * @return the value of stockkdj.stock_history_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getStockHistoryId() {
        return stockHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockkdj.stock_history_id
     *
     * @param stockHistoryId the value for stockkdj.stock_history_id
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setStockHistoryId(Integer stockHistoryId) {
        this.stockHistoryId = stockHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockkdj.trading_date
     *
     * @return the value of stockkdj.trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public Integer getTradingDate() {
        return tradingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockkdj.trading_date
     *
     * @param tradingDate the value for stockkdj.trading_date
     *
     * @mbggenerated Sun Sep 17 15:15:42 CST 2017
     */
    public void setTradingDate(Integer tradingDate) {
        this.tradingDate = tradingDate;
    }
}